attributes:
  - attribute_code: "CUSTGROUP"
    data_type: "LIST"
    data_values:
      - ""
      - "Silver"
      - "Gold"
      - "Black"
      - "Platinum"
      - "STAFF"
    table_name: "PRC_DEAL_TRIG"
