promotion_class:
  - code: "Discount"
    code_zh: "折扣"
    description: "Discount applied at line item or transaction level"
    description_zh: "商品行项目或交易总额折扣"
    class_id: "A"
  - code: "Fixed Quantity/Price"
    code_zh: "固定数量/价格"
    description: "A certain discount or special price associated with a certain set of items, when purchased together"
    description_zh: "购买特定组合商品时享受的折扣或特殊价格"
    class_id: "B"
  - code: "Gift with Purchase"
    code_zh: "购买赠礼"
    description: "A gift is provided to the customer when they purchase certain, defined item(s)"
    description_zh: "顾客购买特定商品时赠送礼品"
    class_id: "C"
  - code: "Buy X Get Y"
    code_zh: "买X送Y"
    description: "The purchase of a certain, defined item allows the customer to receive a different item at no cost or a discount"
    description_zh: "购买特定商品可免费获得其他商品或享受折扣"
    class_id: "D"

promotion_template:
  - subclass_id: "1"
    code: "Spend X$ or more, get Y$ off"
    code_zh: "满X美元减Y美元"
    description: "Discount amount is applied to the subtotal of a transaction"
    description_zh: "折扣金额应用于交易小计"
    class_id: "A"
  - subclass_id: "2"
    code: "Spend X$ or more, get Y% off"
    code_zh: "满X美元打Y折"
    description: "Discount percentage is applied to the subtotal of a transaction"
    description_zh: "折扣百分比应用于交易小计"
    class_id: "A"
  - subclass_id: "3"
    code: "Spend X$ or more, get Y% off"
    code_zh: "满X美元打Y折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "A"
  - subclass_id: "4"
    code: "Purchase X item(s) or more, get Y% off"
    code_zh: "购买X件或以上商品打Y折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "A"
  - subclass_id: "5"
    code: "Purchase every X item(s), get Y% off"
    code_zh: "每购买X件商品打Y折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "A"
  - subclass_id: "6"
    code: "Purchase X item(s) or more, get Y$ off"
    code_zh: "购买X件或以上商品减Y美元"
    description: "Discount amount is applied to the subtotal of a transaction"
    description_zh: "折扣金额应用于交易小计"
    class_id: "A"
  - subclass_id: "7"
    code: "Purchase every X item(s), get Y$ off"
    code_zh: "每购买X件商品减Y美元"
    description: "Discount amount is applied to the subtotal of a transaction"
    description_zh: "折扣金额应用于交易小计"
    class_id: "A"
  - subclass_id: "1"
    code: "Purchase every X item(s) fixed price Y$"
    code_zh: "每购买X件商品固定价格Y美元"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "B"
  - subclass_id: "2"
    code: "Purchase X$ or more, fixed price Y$ (1 set)"
    code_zh: "满X美元固定价格Y美元(1套)"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "B"
  - subclass_id: "3"
    code: "Purchase X$ or more, fixed price Y$ (2 set)"
    code_zh: "满X美元固定价格Y美元(2套)"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "B"
    online_calculation: 1
  - subclass_id: "4"
    code: "Purchase X item(s), fixed price Y$"
    code_zh: "购买X件商品固定价格Y美元"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "B"
  - subclass_id: "99"
    code: "Import fixed price Y$ for mutiple items "
    code_zh: "为多个商品导入固定价格Y美元"
    description: "Fixed price is applied to the line items"
    description_zh: "固定价格应用于商品行项目"
    class_id: "B"
    import: 1
  - subclass_id: "1"
    code: "Purchase every X item(s) get Y item(s) free"
    code_zh: "每购买X件商品赠送Y件商品"
    description: "Free items is applied to the line items"
    description_zh: "免费商品应用于商品行项目"
    class_id: "C"
  - subclass_id: "2"
    code: "Purchase X item(s) or more, get Y item(s) free"
    code_zh: "购买X件或以上商品赠送Y件商品"
    description: "Free items is applied to the line items"
    description_zh: "免费商品应用于商品行项目"
    class_id: "C"
  - subclass_id: "3"
    code: "Purchase X$ or more, get Y item(s) free"
    code_zh: "满X美元赠送Y件商品"
    description: "Free items is applied to the line items"
    description_zh: "免费商品应用于商品行项目"
    class_id: "C"
  - subclass_id: "4"
    code: "Purchase X item(s) and Y item(s), get Z item(s) free"
    code_zh: "购买X件和Y件商品赠送Z件商品"
    description: "Free items is applied to the line items"
    description_zh: "免费商品应用于商品行项目"
    class_id: "C"
  - subclass_id: "1"
    code: "Purchase every X item(s) get Y% off"
    code_zh: "每购买X件商品打Y折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "D"
  - subclass_id: "2"
    code: "Purchase X item(s) or more, get Y% off"
    code_zh: "购买X件或以上商品打Y折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "D"
  - subclass_id: "3"
    code: "Purchase A item(s) and B item(s), get Z% off"
    code_zh: "购买A件和B件商品打Z折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "D"
    #PROMOX-114 PromoX-新增固定搭配 items 的 Fixed price的促销类型
  - subclass_id: "4"
    code: "Purchase A item(s) , B item(s) and C item(s), get Z% off"
    code_zh: "购买A件、B件和C件商品打Z折"
    description: "Discount percentage is applied to the line items"
    description_zh: "折扣百分比应用于商品行项目"
    class_id: "D"


promotion_template_default_p:
  "A": { "0": { 'result':[{'discount_type': 'PERCENT_OFF'}],'item_set':1},
       "1": { 'condition':[{'condition_type': 'Amount','threshold_style':'>='}],
            'result':[{'apply_type': 'Transaction','discount_type':'CURRENCY_OFF','action_qty':''}],
            'item_set':1},
       "2": { 'condition':[{'condition_type': 'Amount','threshold_style':'>='}],
            'result':[{'apply_type': 'Transaction','discount_type':'PERCENT_OFF','action_qty':''}],
            'item_set':1},
       "3": { 'condition':[{'condition_type': 'Amount','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','action_qty':''}],
            'item_set':1},
       "4": { 'condition':[{'condition_type': 'Quantity','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','action_qty':''}],
            'item_set':1},
       "5": { 'condition':[{'condition_type': 'Quantity','threshold_style':'Every Quantity'}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','action_qty':''}],
            'item_set':1},
       "6": { 'condition':[{'condition_type': 'Quantity','threshold_style':'>='}],
            'result':[{'apply_type': 'Transaction','discount_type':'CURRENCY_OFF','action_qty':''}],
            'item_set':1},
       "7": { 'condition':[{'condition_type': 'Quantity','threshold_style':'Every Quantity'}],
            'result':[{'apply_type': 'Transaction','discount_type':'CURRENCY_OFF','action_qty':''}],
            'item_set':1}
     }
  "B": { "0": { 'result':[{'discount_type': 'NEW_PRICE'}] ,'item_set':1},
       "1": { 'condition':[{'condition_type': 'Quantity','threshold_style':'Every Quantity'}],
            'result':[{'apply_type': 'Line','discount_type':'NEW_PRICE'}],
            'item_set':1},
       "2": { 'condition':[{'condition_type': 'Amount','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'NEW_PRICE'}],
            'item_set':1},
       "3": { 'condition':[{'condition_type': 'Amount','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'NEW_PRICE'}],
            'item_set':2},
       "4": { 'condition':[{'condition_type': 'Quantity','threshold_style':'Every Quantity'}],
            'result':[{'apply_type': 'Line','discount_type':'NEW_PRICE','action_qty':''}],
            'item_set':0},
       "99": { 'condition':[{'condition_type': 'Quantity','threshold_style':'Every Quantity'}],
            'result':[{'apply_type': 'Line','discount_type':'NEW_PRICE'}],
            'item_set':0},
     }
  "C": { "0": { 'result':[{'discount_type':'PERCENT_OFF'}],'item_set':2},
       "1": { 'condition':[{'condition_type': 'Quantity','threshold_style':'Every Quantity'}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','discount_value':'100'}],
            'item_set':2},
       "2": { 'condition':[{'condition_type': 'Quantity','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','discount_value':'100'}],
            'item_set':2},
       "3": { 'condition':[{'condition_type': 'Amount','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','discount_value':'100'}],
            'item_set':2},
       "4": { 'condition':[{'condition_type': 'Quantity','threshold_style':'>='},{'condition_type': 'Quantity','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF','discount_value':'100'}],
            'item_set':2}
     }
  "D": { "0": { 'result':[{'discount_type':'PERCENT_OFF'}],'item_set':2},
       "1": { 'condition': [ { 'condition_type': 'Quantity','threshold_style': 'Every Quantity' }],
            'result': [ { 'apply_type': 'Line','discount_type': 'PERCENT_OFF' } ],'item_set': 2 },
       "2": { 'condition': [{'condition_type': 'Quantity'}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF'}],'item_set':2},
       "3": { 'condition': [{'condition_type': 'Quantity','threshold_style':'>='},{'condition_type': 'Quantity','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF'}],'item_set':2},
        #PROMOX-114 PromoX-新增固定搭配 items 的 Fixed price的促销类型
       "4": { 'condition': [{'condition_type': 'Quantity','threshold_style':'>='},{'condition_type': 'Quantity','threshold_style':'>='},{'condition_type': 'Quantity','threshold_style':'>='}],
            'result':[{'apply_type': 'Line','discount_type':'PERCENT_OFF'}],'item_set':2}
     }

