promotion_mapping:
  DEAL:
    organization_id: 1
    org_code: "*"
    org_value: "*"
    generosity_cap: 999999999
    iteration_cap: -1
    exclude_discounted_flag: 0
  DEAL_P:
    organization_id: 1
    property_code: "STACKABLE"
    type: "String"
  DEAL_ITEM_1:
    organization_id: 1
    org_code: "*"
    org_value: "*"
  DEAL_ITEM_2:
    organization_id: 1
    org_code: "*"
    org_value: "*"
  DEAL_ITEM_TEST:
    organization_id: 1
    org_code: "*"
    org_value: "*"
    value1: "TRUE"
  PRC_DEAL_LOC:
    organization_id: 1
  PRC_DEAL_TRIG:
    organization_id: 1
    org_code: "*"
    org_value: "*"
  DSC_COUPON_XREF:
    organization_id: 1
    org_code: "*"
    org_value: "*"
    coupon_type: "INPUT_COUPON"
    serialized_flag: 0
    effective_date: "2019-01-01"

segment_mapping:
  ITM_ITEM_DEAL_PROP:
    organization_id: 1
    org_code: "*"
    org_value: "*"
    type: "STRING"
    string_value: "TRUE"

commission_mapping:
  COM_CODE_VALUE_P:
    organization_id: 1
    category: "SAM_COMMISSION"
    type: "DECIMAL"
  COM_CODE_VALUE:
    organization_id: 1
    category: "SAM_COMMISSION"
    CONFIG_ELEMENT: "*"
  COM_TRANS_PROMPT_PROPERTIES:
    organization_id: 1
    org_code: "*"
    org_value: "*"
    effective_date: "1900-01-01 00:00:00"
    expiration_date: "2099-01-01 00:00:00"
    code_category: "SAM_COMMISSION"
    prompt_title_key: "_samCommissionPatternTitle"
    prompt_msg_key: "_samCommissionPatternMsg"
    required_flag: 1
    sort_order: 10
    prompt_mthd_code: "LIST"
    transaction_state: "PRE_SALE"
  COM_TRANSLATIONS:
    organization_id: 1
    locale: "DEFAULT"
    org_code: "*"
    org_value: "*"