name: Build Windows Installer with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build EXE and Installer for Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'


      - name: Install SQL Server ODBC Driver
        run: |
          # 使用Microsoft提供的脚本安装
          powershell -Command "Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/?linkid=2209524' -OutFile 'msodbcsql17.msi'"

          # 检查文件是否成功下载
          if (!(Test-Path "msodbcsql17.msi")) {
            echo "Error: Failed to download msodbcsql17.msi"
            exit 1
          }

          # 获取文件大小验证下载
          $fileSize = (Get-Item "msodbcsql17.msi").Length
          if ($fileSize -lt 1000000) {
            echo "Error: Downloaded file size is too small: $fileSize bytes"
            exit 1
          }

          # 安装ODBC驱动
          msiexec /i msodbcsql17.msi /quiet /passive /norestart IACCEPTMSODBCSQLLICENSETERMS=YES

          # 验证安装结果
          if (!$?) {
            echo "Error: Failed to install SQL Server ODBC Driver"
            exit 1
          }

          # 验证驱动程序安装（修复PowerShell语法）
          powershell -Command "Get-OdbcDriver | Where-Object { `$_.Name -like '*SQL Server*' }"

      - name: Install dependencies
        run: |    
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install NSIS
        run: |
          choco install nsis -y
          refreshenv

      - name: Build EXE with PyInstaller
        run: |
          python -m PyInstaller --onefile --hidden-import=pyodbc --name XPromo main.py

      - name: Prepare config files
        run: |
          # 创建配置文件目录
          mkdir dist\config
          
          # 复制配置文件到安装包目录
          copy config\*.yaml dist\config\
          copy config\*.py dist\config\
          
          # 创建配置文件模板目录（用于安装时选择是否覆盖）
          mkdir dist\config_templates
          copy config\*.yaml dist\config_templates\
          copy config\*.py dist\config_templates\

      - name: Debug information
        run: |    
          echo "Current directory contents:"
          dir
          echo "Dist directory contents:"
          dir "dist"

      - name: Create installer with NSIS
        run: |
          if (!(Test-Path "dist\XPromo.exe")) {
            echo "Error: dist\XPromo.exe not found, cannot create installer"
            exit 1
          }
          
          # 创建安装脚本
          echo '!include "MUI2.nsh"' > installer.nsi
          echo '' >> installer.nsi
          echo 'Name "XPromo"' >> installer.nsi
          echo 'OutFile "dist\XPromo-Installer.exe"' >> installer.nsi
          echo 'InstallDir $PROGRAMFILES\XPromo' >> installer.nsi
          echo 'RequestExecutionLevel admin' >> installer.nsi
          echo '' >> installer.nsi
          
          # 定义安装页面
          echo '!define MUI_ABORTWARNING' >> installer.nsi
          echo '!insertmacro MUI_PAGE_WELCOME' >> installer.nsi
          echo '!insertmacro MUI_PAGE_DIRECTORY' >> installer.nsi
          echo '!insertmacro MUI_PAGE_INSTFILES' >> installer.nsi
          echo '!insertmacro MUI_PAGE_FINISH' >> installer.nsi
          echo '' >> installer.nsi
          
          # 定义卸载页面
          echo '!insertmacro MUI_UNPAGE_CONFIRM' >> installer.nsi
          echo '!insertmacro MUI_UNPAGE_INSTFILES' >> installer.nsi
          echo '' >> installer.nsi
          
          # 语言设置
          echo '!insertmacro MUI_LANGUAGE "English"' >> installer.nsi
          echo '' >> installer.nsi
          
          # 安装部分
          echo 'Section "XPromo"' >> installer.nsi
          echo '  SectionIn RO' >> installer.nsi
          echo '  SetOutPath $INSTDIR' >> installer.nsi
          echo '  File "dist\XPromo.exe"' >> installer.nsi
          echo '' >> installer.nsi
          echo '  SetOutPath $INSTDIR\config' >> installer.nsi
          echo '  File "dist\config\*.*"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo '' >> installer.nsi
          
          # 配置文件部分（可选安装）
          echo 'Section "Config Files (Overwrite)"' >> installer.nsi
          echo '  SetOutPath $INSTDIR\config' >> installer.nsi
          echo '  File "dist\config_templates\*.*"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo '' >> installer.nsi
          
          # 创建开始菜单快捷方式
          echo 'Section "Start Menu Shortcuts"' >> installer.nsi
          echo '  CreateDirectory "$SMPROGRAMS\XPromo"' >> installer.nsi
          echo '  CreateShortCut "$SMPROGRAMS\XPromo\XPromo.lnk" "$INSTDIR\XPromo.exe"' >> installer.nsi
          echo '  CreateShortCut "$SMPROGRAMS\XPromo\Uninstall.lnk" "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo '' >> installer.nsi
          
          # 注册表信息
          echo 'Section -Post' >> installer.nsi
          echo '  WriteUninstaller "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo '  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\XPromo" "DisplayName" "XPromo"' >> installer.nsi
          echo '  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\XPromo" "UninstallString" "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo '  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\XPromo" "DisplayIcon" "$INSTDIR\XPromo.exe"' >> installer.nsi
          echo '  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\XPromo" "Publisher" "XPromo"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo '' >> installer.nsi
          
          # 卸载部分
          echo 'Section Uninstall' >> installer.nsi
          echo '  Delete "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo '  Delete "$INSTDIR\XPromo.exe"' >> installer.nsi
          echo '  Delete "$INSTDIR\config\*.*"' >> installer.nsi
          echo '  RMDir "$INSTDIR\config"' >> installer.nsi
          echo '  RMDir "$INSTDIR"' >> installer.nsi
          echo '' >> installer.nsi
          echo '  Delete "$SMPROGRAMS\XPromo\*.*"' >> installer.nsi
          echo '  RMDir "$SMPROGRAMS\XPromo"' >> installer.nsi
          echo '' >> installer.nsi
          echo '  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\XPromo"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          
          # 显示当前目录和文件信息用于调试
          echo "Current working directory:"
          pwd
          echo "Full path to XPromo.exe:"
          $exePath = Resolve-Path "dist\XPromo.exe"
          echo $exePath
          
          & "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

      - name: Archive installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: XPromo-installer
          path: dist/XPromo-Installer.exe
